// Exportar todos los servicios desde un punto central
export { default as apiClient } from "./api"
export { default as sesion } from "./sesion"
export { default as catalogos } from "./catalogos"
export { default as creditos } from "./creditos"
export { pagosPendientes } from "./pagosPendientes"
export { registroPagos } from "./registroPagos"
export { default as resumenDiario } from "./resumenDiario"
export { resumenCobranza } from "./resumenCobranza"
export { rutaCobranzaEjecutivo } from "./rutaCobranzaEjecutivo"
export { detalleSemanalEjecutivo } from "./detalleSemanalEjecutivo"
